spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2

code:
  exp: ${CODE_EXP}

mail:
  email: ${MY_EMAIL}

jwt:
  secret_key: ${SECRET_KEY}
  access_exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}
  header: ${HEADER}
  prefix: ${PREFIX}
